# Generated by Django 2.2.1 on 2019-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaksung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('writer', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
